
site_name: BRES Documentation
nav:
  - Home: index.md
  - System Overview: system_overview.md
  - Phase Assignment: phase_assignment.md
  - Feature Extraction: feature_extraction.md
  - Classification: classification.md
  - Interpretation: interpretation.md
  - Developer Guide: developer_guide.md
  - Use Cases: use_cases.md
  - Architecture: architecture.md
  - Workflow Examples: workflow_examples.md
  - References: references.md
  - Ritual Classifier: ritual_classifier.md 
